Models/ConsultationModel.cs
using System;
using System.ComponentModel.DataAnnotations; // Підключення бібліотеки для атрибутів валідації
using AspNetCoreConsultationForm.Settings;

public class ConsultationModel
{
    [Required(ErrorMessage = "First and last name are required")] // Атрибут, що вказує на обов'язковість поля
    public string Name { get; set; }

    [Required(ErrorMessage = "Email is required")]
    [EmailAddress(ErrorMessage = "Please enter a valid Email")] // Атрибут, що перевіряє коректність формату Email
    public string Email { get; set; }

    [Required(ErrorMessage = "The desired consultation date is required")]
    [DataType(DataType.Date)] // Атрибут, що вказує на тип даних (дата)
    [FutureDate(ErrorMessage = "The desired date must be in the future")] // Атрибут, що перевіряє чи вибрана дата у майбутньому
    [NotOnMonday(ErrorMessage = "The desired date must not be a weekend")] //Аатрибут, що перевіряє чи не є вибрана дата понеділком
    public DateTime ConsultationDate { get; set; }

    [Required(ErrorMessage = "Please select a product")]
    public string SelectedProduct { get; set; }
}

Models/ErrorViewModel.cs
namespace AspNetMVC.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Controllers/CalcController.cs
public class CalcController
{
    private CalcService calcService;

    // Приймає CalcService для обробки математичних операцій
    public CalcController(CalcService calcService)
    {
        this.calcService = calcService;
    }

    public double Add(double a, double b)
    {
        return calcService.Add(a, b);
    }

    public double Subtract(double a, double b)
    {
        return calcService.Subtract(a, b);
    }

    public double Divide(double a, double b)
    {
        return calcService.Divide(a, b);
    }

    public double Multiply(double a, double b)
    {
        return calcService.Multiply(a, b);
    }
}

Controllers/ConsultationController.cs
using AspNetMVC.Models;
using Microsoft.AspNetCore.Mvc;

public class ConsultationController : Controller
{
    public IActionResult Index()
    {
        return View();
    }

    [HttpPost]
    public string Consultation(ConsultationModel model)
    {
        if (ModelState.IsValid) // Перевірка на валідність введених даних
        {
            return $"Дані пройшли валідацію: {model.Name} - {model.Email} - {model.ConsultationDate} - {model.SelectedProduct}";
            // Повертає рядок із валідними даними консультації
        }
        return "Дані не пройшли валідацію"; // Повертає повідомлення про невалідність даних
    }
}

Controllers/HomeController.cs
using System.Diagnostics;
using AspNetMVC.Models;
using Microsoft.AspNetCore.Mvc;

namespace AspNetMVC.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(
                new ErrorViewModel
                {
                    RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier
                }
            );
        }
    }
}

Views/Consultation/Index.cshtml
@model ConsultationModel

<h2>Реєстрація на консультацію</h2>

<form method="post" asp-controller="Consultation" asp-action="Consultation">
    <div class="form-group">
        <label asp-for="Name">Ваше ім'я:</label>
        <input asp-for="Name" class="form-control" placeholder="required field for input" />
        <span asp-validation-for="Name" class="text-danger"></span>
    </div>

    <div class="form-group">
        <label asp-for="Email">Email:</label>
        <input asp-for="Email" class="form-control" />
        <span asp-validation-for="Email" class="text-danger"></span>
    </div>

    <div class="form-group">
        <label asp-for="ConsultationDate">Бажана дата консультації:</label>
        <input asp-for="ConsultationDate" type="date" class="form-control" />
        <span asp-validation-for="ConsultationDate" class="text-danger"></span>
    </div>

    <div class="form-group">
        <label asp-for="SelectedProduct">Продукт для консультації:</label>
        <select asp-for="SelectedProduct" class="form-control">
            <option value="">Select a product</option>
            <option value="JavaScript">JavaScript</option>
            <option value="C#">C#</option>
            <option value="Java">Java</option>
            <option value="Python">Python</option>
            <option value="Основи">Основи</option>
        </select>
        <span asp-validation-for="SelectedProduct" class="text-danger"></span>
    </div>

    <button type="submit" class="btn btn-primary">Зареєструватися</button>
</form>

Views/File/DownloadFile.cshtml
@model CreateFile.Models.FileViewModel
<link rel="stylesheet" href="~/css/styles.css" />

<h2>Форма завантаження файлу</h2>

<form asp-controller="File" asp-action="DownloadFile" method="post">
    <div class="form-group">
        <label asp-for="FirstName">Ім'я:</label>
        <input asp-for="FirstName" class="form-control" required />
    </div>
    <div class="form-group">
        <label asp-for="LastName">Прізвище:</label>
        <input asp-for="LastName" class="form-control" required />
    </div>
    <div class="form-group">
        <label for="fileName">Назва файлу:</label>
        <input type="text" id="fileName" name="fileName" class="form-control" required />
    </div>
    <button type="submit" class="btn btn-primary">Продовжити</button>
</form>

Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

Views/Product/OrderPizza.cshtml
@model PizzaApp.Models.User
<link rel="stylesheet" href="~/css/styles.css" />

<h2>Вітаємо!</h2>
<h3>Будь ласка, оберіть піцци для замовлення:</h3>
<form asp-action="OrderPizza" method="post">
    @for (var i = 0; i < Model.Products.Count; i++)
    {
        <div class="form-group">
            <label asp-for="Products[i].Name">Назва:</label>
            <input asp-for="Products[i].Name" class="form-control" readonly />
            <label asp-for="Products[i].Price">Ціна:</label>
            <input asp-for="Products[i].Price" class="form-control" readonly />
            <label asp-for="Products[i].Quantity">Кількість:</label>
            <input asp-for="Products[i].Quantity" class="form-control" />
        </div>
    }
    <button type="submit" class="btn btn-primary">Створити замовлення</button>
</form>

Views/Product/OrderSummary.cshtml
<link rel="stylesheet" href="~/css/styles.css" />

<h2>Дякуємо за замовлення!</h2>

@{
    decimal totalAmount = 0;
}

<table class="table">
    <thead>
        <tr>
            <th>Піцца</th>
            <th>Кільксть</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var product in Model.Products)
        {
            if (product.Quantity > 0)
            {
                <tr>
                    <td>@product.Name</td>
                    <td>@product.Quantity</td>
                </tr>
                totalAmount += product.Price * product.Quantity;
            }
        }
    </tbody>
</table>

<p>Загальна сума замовлення: @totalAmount</p>

Views/Product/ProductsTable.cshtml
<h2>Таблиця продуктів</h2>
<table class="table">
    <thead>
        <tr>
            <th>ID</th>
            <th>Name</th>
            <th>Price</th>
        </tr>
    </thead>
    @foreach (var product in Model)
    {
        <tr>
            <td>@product.ID</td>
            <td>@product.Name</td>
            <td>@product.Price $</td>
        </tr>
    }
</table>

Views/Product/RegisterUser.cshtml
@model PizzaApp.Models.User
<link rel="stylesheet" href="~/css/styles.css" />

<h2>Будь ласка, зареєструйтеся для здійсненя замовлення</h2>

<form asp-action="RegisterUser" method="post">
    <div class="form-group">
        <label asp-for="Name">Ім'я:</label>
        <input asp-for="Name" class="form-control" />
    </div>
    <div class="form-group">
        <label asp-for="LastName">Прізвище:</label>
        <input asp-for="LastName" class="form-control" />
    </div>
    <div class="form-group">
        <label asp-for="Phone">Номер телефону:</label>
        <input asp-for="Phone" class="form-control" />
    </div>
    <div class="form-group">
        <label asp-for="Age">Вік:</label>
        <input asp-for="Age" class="form-control" />
    </div>
    <button type="submit" class="btn btn-primary">Зареєструватися</button>
</form>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - AspNetMVC</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/AspNetMVC.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">AspNetMVC</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Consultation" asp-action="Index">Consultation</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - AspNetMVC - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="~/lib/jquery-validation/dist/jquery.validate.min.js"></script>
    <script src="~/lib/jquery-validation-unobtrusive/dist/jquery.validate.unobtrusive.min.js"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>